[default_config]
version = "0.10.0"
assembler = "nasm"
instruction_set = "x86/x86-64"

[default_config.opts]
compiler = "nasm"
compile_flags_txt = ["-felf64"]
diagnostics = true
default_diagnostics = true
